server:
  port: 8090
  servlet:
    context-path: /api


spring:
  application:
    name: book
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
      show-sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database: mysql
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

debug: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include: *


